# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - id: till_darwin
    binary: till
    main: main.go
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -tags
      - sqlite

  - id: till_linux
    binary: till
    main: main.go
    env:
      - CGO_ENABLED=1
    flags:
      - -tags
      - sqlite
    goos:
      - linux
    goarch:
      - amd64
      - 386

  - id: till_windows_i686
    binary: till
    main: main.go
    ldflags:
      - "-extldflags '-static'"
    env:
      - CGO_ENABLED=1
      - CC=i686-w64-mingw32-gcc
      - CXX=i686-w64-mingw32-g++
    flags:
      - -tags
      - sqlite
    goos:
      - windows
    goarch:
      - 386

  - id: till_windows_x64
    binary: till
    main: main.go
    ldflags:
      - "-extldflags '-static'"
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags:
      - -tags
      - sqlite
    goos:
      - windows
    goarch:
      - amd64

archives:
  - replacements:
      darwin: Darwin_MacOS
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  prerelease: auto